//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Exception
{
    using System;
    using System.Collections.Generic;
    
    public partial class regional
    {
        public long id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string image { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<System.DateTime> date_update { get; set; }
        public string created_by { get; set; }
        public string updated_by { get; set; }
        public Nullable<bool> is_active { get; set; }
        public long national_id { get; set; }
    }
}
